# SFM SOCK: Close_Server.py
# This software is licensed under the MIT License.
# Copyright (c) 2021 KiwifruitDev

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import sfm

# Make sure SFMSOCK exists.
if "SFMSOCK" in globals():
    # We're good to go.
    SFMSOCK = globals()["SFMSOCK"]
    SFMSOCK.close()
else:
    sfm.Msg("SFM SOCK is not running, this script can not be run.\n")
